name: flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  intl: ^0.15.5

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_scripta.png 
    - assets/images/no_content.jpg
    - assets/images/capa_livro.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
